### ISSUE TITLE
Add docs

### ISSUE THREAD

**Issue by LauraBeatris** [LauraBeatris/floripamais-strapi-api#3]
# Tasks 

- [x] Add base project docs
- [x] Add logo 
- [x] Add instructions to run the CMS locally
- [x] Link the website 
- [x] Add contributing guidelines
