### ISSUE TITLE
Customize admin painel

### ISSUE THREAD

**Issue by LauraBeatris** [LauraBeatris/floripamais-strapi-api#5]
## Description 

Customize admin panel to remove default styles and assets from Strapi and be more related to the Floripa+ organization 

## Tasks 

- [x] Customize admin panel logo
- [x] Customize login screen logo 
- [x] Customize auth pages 
- [x] Customize admin panel colors

**Comment by LauraBeatris** [comment]
Fix misspell of component -> `BaselineAlignement`

**Comment by LauraBeatris** [comment]
Centralize auth page boxes by default

**Comment by LauraBeatris** [comment]
Add portuguese translation
